name: crawl

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci

      - env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          PING_URL_YAML: ${{ secrets.PING_URL_YAML }}
        run: |
          git config user.email ${GIT_USER_EMAIL}
          git config user.name ${GIT_USER_NAME}
          echo "$PING_URL_YAML" > data/pingURL.yaml

      - env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm start
